[Variables]
; ============ Global Settings ============

Language=0
; Default font = Montserrat
; Montserrat Alternate for monospace number
NumberFont=Montserrat Alternates Light
LetterFont=Montserrat
TextStyle=Normal
TextEffect=Border
TextColor=255,255,255,255
LineColor=255,255,255,155
ShadowColor=0,0,0,35
BackgroundColor=55,55,155,0

;Weather (Loc.code - код города на weather.com для погоды)
WeatherCode=RSXX0082:1:RS
Type=m
Image1=#@#Images\[MeasureImageThe].png
WeatherImageAlpha=255

;Hdd
Drive1=C
Drive2=D

; ============ Locale Settings ============
CPUBottom=1
CPURight=1
CPULeft=0
CPUTop=1

TimeBottom=0
TimeRight=1
TimeLeft=1
TimeTop=0
TimeAlign=Center

RAMBottom=1
RAMRight=1
RAMLeft=1
RAMTop=1

WeatherBottom=1
WeatherRight=0
WeatherLeft=1
WeatherTop=1

DriveBottom=1
DriveRight=1
DriveLeft=0
DriveTop=1
