[Variables]
; ============ Global Settings ============

Language=1
; Default font = Montserrat
; Montserrat Alternate for monospace number
NumberFont=Montserrat Alternates Light
LetterFont=Montserrat
TextStyle=none
TextEffect=none
TextColor=255,255,255,255
LineColor=255,255,255,155
ShadowColor=0,0,0,35
BackgroundColor=0,100,255,55

;Weather (Loc.code - код города на weather.com для погоды)
WeatherCode=RSXX0082:1:RS
Type=m
Image1=WeatherIcons\[MeasureImageThe].png

;Hdd
Drive1=C
Drive2=D

; ============ Locale Settings ============
CPUBottom=0
CPURight=0
CPULeft=0
CPUTop=0

TimeBottom=0
TimeRight=0
TimeLeft=0
TimeTop=0
TimeAlign=Center

RAMBottom=0
RAMRight=0
RAMLeft=0
RAMTop=0

WeatherBottom=0
WeatherRight=0
WeatherLeft=0
WeatherTop=0

DriveBottom=0
DriveRight=0
DriveLeft=0
DriveTop=0
