[Variables]
Color=255,255,255,255
Color2=255,255,255,55
Color3=0,0,0,35
Font=Montserrat 
Font2=Montserrat
Style=Normal
Style2=none
Rus=1
Eng=0

;Line
CPUBottom=0
CPURight=0
CPULeft=0
CPUTop=0

TimeBottom=0
TimeRight=0
TimeLeft=0
TimeTop=0

RAMBottom=0
RAMRight=0
RAMLeft=0
RAMTop=0

WeatherBottom=0
WeatherRight=0
WeatherLeft=0
WeatherTop=0

;Weather (Loc.code - код города на weather.com для погоды)
WeatherCode=RSXX0082:1:RS
Type=m
Image1=WeatherIcons\[MeasureImageThe].png

;Hdd
disk1=C
disk2=D
